"""Curated therapeutic antibody reference panel.

Contains variable-domain sequences from clinically approved monoclonal
antibodies spanning humanised, fully human, and chimeric formats across
oncology, autoimmune/inflammation, and checkpoint-inhibitor indications.
The panel includes heavy chains, kappa light chains, and lambda light
chains to support broad developability benchmarking.

Note: this is an MVP reference set.  Production systems should integrate
ANARCI / AbNumber for robust numbering and IgBLAST for germline inference.
"""

EXAMPLE_SEQUENCES = {
    # ===================================================================
    # HEAVY CHAINS
    # ===================================================================

    # -- Humanised --
    "Trastuzumab VH": (
        "EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGR"
        "FTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSS"
    ),
    "Bevacizumab VH": (
        "EVQLVESGGGLVQPGGSLRLSCAASGYTFTNYGMNWVRQAPGKGLEWVGWINTYTGEPTYAADFKRR"
        "FTFSLDTSKSTAYLQMNSLRAEDTAVYYCAKYPHYYGSSHWYFDVWGQGTLVTVSS"
    ),
    "Eculizumab VH": (
        "QVQLVQSGAEVKKPGSSVKVSCKASGYTITDQYIHWVRQAPGQGLEWMGWIHPNSGNTNYAQKFQG"
        "RVTMTRDTSISTAYMELSRLRSDDTAVYYCARLVYGTNFFDYWGQGTLVTVSS"
    ),
    "Natalizumab VH": (
        "QVQLVQSGAEVKKPGASVKVSCKASGFNIKDTYIHWVRQAPGQGLEWMGRIDPANGYTKYDPKFQG"
        "RVTMTRDTSISTAYMELSRLRSDDTAVYYCAREGYYGNYGVYAMDYWGQGTLVTVSS"
    ),

    # -- Fully human --
    "Adalimumab VH": (
        "EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLEWVSAITWNSGHIDYADSVEGR"
        "FTISRDNAKNSLYLQMNSLRAEDTAVYYCAKVSYLSTASSLDYWGQGTLVTVSS"
    ),
    "Pembrolizumab VH": (
        "QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGIINPSNGGTNFNEKFKNR"
        "VTMTRDTSISTAYMELSSLRSEDTAVYYCARRDYRFDMGFDYWGQGTTVTVSS"
    ),
    "Nivolumab VH": (
        "QVQLVESGGGVVQPGRSLRLDCKASGITFSNSGMHWVRQAPGKGLEWVAVIWYDGSKRYYADSVKG"
        "RFTISRDNSKNTLFLQMNSLRAEDTAVYYCATNDDYWGQGTLVTVSS"
    ),
    "Secukinumab VH": (
        "EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYWMSWVRQAPGKGLEWVANIKQDGSEKYYVDSVKGR"
        "FTISRDNAKNSLYLQMNSLRAEDTAVYYCARDRIAATGFDYWGQGTLVTVSS"
    ),

    # -- Chimeric --
    "Rituximab VH": (
        "QVQLQQPGAELVKPGASVKMSCKASGYTFTSYNMHWVKQTPGRGLEWIGAIYPGNGDTSYNQKFKG"
        "KATLTADKSSSTAYMQLSSLTSEDSAVYYCARSTYYGGDWYFNVWGAGTTVTVSA"
    ),
    "Cetuximab VH": (
        "QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLEWLGVIWSGGNTDYNTPFTSR"
        "LSINKDNSKSQVFFKMNSLQSNDTAIYYCARALTYYDYEFAYWGQGTLVTVSA"
    ),

    # -- Checkpoint inhibitors --
    "Atezolizumab VH": (
        "EVQLVESGGGLVQPGGSLRLSCAASGFTFSDSWIHWVRQAPGKGLEWVAWISPYGGSTYYADSVKGR"
        "FTISADTSKNTAYLQMNSLRAEDTAVYYCARRHWPGGFDYWGQGTLVTVSS"
    ),

    # ===================================================================
    # KAPPA LIGHT CHAINS
    # ===================================================================
    "Trastuzumab VL": (
        "DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSG"
        "TDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIK"
    ),
    "Adalimumab VL": (
        "DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKLLIYAASTLQSGVPSRFSGSGS"
        "GTDFTLTISSLQPEDIATYYCQRYNRAPYTFGQGTKVEIK"
    ),
    "Bevacizumab VL": (
        "DIQMTQSPSSLSASVGDRVTITCSASQDISNYLNWYQQKPGKAPKVLIYFTSSLHSGVPSRFSGSGS"
        "GTDFTLTISSLQPEDFATYYCQQYSTVPWTFGQGTKVEIK"
    ),
    "Rituximab VL": (
        "QIVLSQSPAILSASPGEKVTMTCRASSSVSYIHWFQQKPGSSPKPWIYATSNLASGVPVRFSGSGS"
        "GTSYSLTISRVEAEDAATYYCQQWTSNPPTFGGGTKLEIK"
    ),
    "Pembrolizumab VL": (
        "EIVLTQSPATLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGS"
        "GTDFTLTISSLEPEDFAVYYCQQSSNWPRTFGQGTKVEIK"
    ),
    "Nivolumab VL": (
        "EIVLTQSPATLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGS"
        "GTDFTLTISSLEPEDFAVYYCQQSSNWPRTFGQGTKVEIK"
    ),
    "Cetuximab VL": (
        "DILLTQSPVILSVSPGERVSFSCRASQSIGTNIHWYQQRTNGSPRLLIKYASESISGIPSRFSGSGS"
        "GTDFTLSINSVESEDIADYYCQQNNNWPTTFGAGTKLELK"
    ),
    "Secukinumab VL": (
        "EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGS"
        "GTDFTLTISRLEPEDFAVYYCQQYGSSPCTFGQGTKVEIK"
    ),

    # ===================================================================
    # LAMBDA LIGHT CHAINS
    # ===================================================================
    "Eculizumab VL": (
        "QSALTQPASVSGSPGQSITISCTGTSSDVGGYNYVSWYQQHPGKAPKLMIYEVSNRPSGVSNRFSGS"
        "KSGNTASLTISGLQAEDEADYYCSSYTSSSTRVFGTGTKVTVL"
    ),
    "Natalizumab VL": (
        "DIQMTQSPSSLSASVGDRVTITCRASQTIWSYLNWYQQKPGKAPNLLIYAASSLQSGVPSRFSGSGS"
        "GTDFTLTISSLQPEDFATYYCQQSYSIPLTFGQGTKVEIK"
    ),
}
